name: Dash App CI

on:
  push:
    branches:
      - main


jobs:
  # Step 1: Test the app using Docker
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker image for testing
      - name: Build Docker image for testing
        run: docker build -t prediction_v3 -f code/Dockerfile code

      # Run tests inside the Docker container
      - name: Run tests in Docker
        run: docker run prediction_v3 pytest

  build:
    runs-on: ubuntu-latest
    needs: test  # Build only after tests pass
    
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build the Docker image for the app
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/prediction_v3:latest -f code/Dockerfile code
      # Push the image to DockerHub
      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/prediction_v3:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ vars.PROXY_HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_key: ${{ secrets.PROXY_KEY }}
          script: |
            docker pull bidhan01/prediction_v3:latest
            docker compose -f st125287/docker-compose.yaml down --remove-orphans
            docker compose -f st125287/docker-compose.yaml up -d